### ISSUE TITLE
fix & re-enable stacking, Boston flux and crabs

### ISSUE THREAD

**Issue by tlienart** [JuliaAI/DataScienceTutorials.jl#159]
Context: https://github.com/alan-turing-institute/DataScienceTutorials.jl/pull/154#issuecomment-891636480

cc: @ablaom

**Comment by tlienart** [comment]
done

**Comment by ablaom** [comment]
Yes, while the stacking tutorial is still failing (because, I believe of external bug) this is tracked by https://github.com/JuliaAI/DataScienceTutorials.jl/issues/162 .
